export const tableHeaders = [
  {
    label: 'Articel No',
    field: 'artnr',
    name: 'artnr',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Description',
    field: 'bezeich',
    name: 'bezeich',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Const',
    field: 'endkum',
    name: 'endkum',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Quantity',
    field: 'anzahl',
    name: 'anzahl',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Unit Price',
    field: 'einzelpreis',
    name: 'einzelpreis',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Amount',
    field: 'warenwert',
    name: 'warenwert',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Arrival Date',
    field: 'lieferdatum-eff',
    name: 'lieferdatum-eff',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Delive D-Unit',
    field: 'geliefert',
    name: 'geliefert',
    align: 'left',
    sortable: false,
  },
  {
    label: 'S-Unit',
    field: 'zeit',
    name: 'zeit',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Actual Price',
    field: 'rechnungspreis',
    name: 'rechnungspreis',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Amount',
    field: 'rechnungswert',
    name: 'rechnungswert',
    align: 'left',
    sortable: false,
  },
];

export const DeliveryNumber = [
  {
    label: 'Date',
    field: 'datum',
    name: 'datum',
    align: 'left',
    sortable: false,
  },
  {
    label: 'St',
    field: 'lager-nr',
    name: 'lager-nr',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Document Number',
    field: 'docu-nr',
    name: 'docu-nr',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Delivery Number',
    field: 'lscheinnr',
    name: 'lscheinnr',
    align: 'left',
    sortable: false,
  },
]
