import { TableHeader } from '~/components/VhpUI/typings';

export const tableHeaders: TableHeader[] = [
    {
        label: 'Date',
        field: 'descr',
        name: 'descr',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Delivery Number',
        field: 'cost-alloc',
        name: 'cost-alloc',
        sortable: false,
    },
    {
        label: 'From Storage',
        field: 'today-consume',
        name: 'today-consume',
        align: 'right',
        sortable: false,
    },
    {
        label: 'To Storage',
        field: 'mtd-consume',
        name: 'mtd-consume',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Article Number',
        field: 'mtd-consume',
        name: 'mtd-consume',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Description',
        field: 'mtd-consume',
        name: 'mtd-consume',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Unit',
        field: 'mtd-consume',
        name: 'mtd-consume',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Content',
        field: 'mtd-consume',
        name: 'mtd-consume',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Average Price',
        field: 'mtd-consume',
        name: 'mtd-consume',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Quantity',
        field: 'mtd-consume',
        name: 'mtd-consume',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Amount',
        field: 'mtd-consume',
        name: 'mtd-consume',
        align: 'right',
        sortable: false,
    },
    {
        label: 'ID',
        field: 'mtd-consume',
        name: 'mtd-consume',
        align: 'right',
        sortable: false,
    },
];